[theme]
base="dark"

# Primary accent for interactive elements
primaryColor = '#EABB26'

# Background color for the main content area
backgroundColor = '#061838'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FFFFFF'

# Color used for almost all text
textColor = '#F7F7F7'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"